## upload button
library(shiny)
library(shinyjs)
library(dplyr)
library(readr)
library(sf)
library(lubridate)
library(magrittr)
library(leaflet)
library(rtide)
library(poisspatial)
library(scales)
library(DT)
library(shinyWidgets)
library(dygraphs)
library(shinyBS)

#slackr
slackr::slackr_setup(config_file = "./.slackr")

source('functions.R', local = TRUE)
poisson_logo <- actionLink(inputId = 'poisson', 
                           label = img(src = 'poisson-logo.png',
                                       height = 177/5,
                                       width = 739/5,
                                       onclick = "window.open('http://www.poissonconsulting.ca', '_blank')"))


###### ------ modules
source('modules/about-server.R', local = TRUE)
source('modules/about-ui.R', local = TRUE)
source('modules/map-server.R', local = TRUE)
source('modules/map-ui.R', local = TRUE)

### ui vars
proj.description <- "Display tidal predictions generated by the rtide R package."
proj <- "U.S. Tidal Predictions"

mapbox_moon <- "https://api.mapbox.com/styles/v1/sebpoisson/cjjfvxsqh1nrd2rnqabh10sx4/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1Ijoic2VicG9pc3NvbiIsImEiOiJjamk1YXBiYm4waHd0M2twNmM3ODRuZjN4In0.WKHsGJ3K7SWyqO4lObCkfA
"
disclaimer <- "Tide predictions are generated using the rtide R package and are not suitable for navigation.
                                      For more information about rtide, see https://github.com/poissonconsulting/rtide."

initial_lat <- 43
initial_long <- -120
initial_zoom <- 3
click_zoom <- 11
leaf.pos <- "topleft"
sidepanel.width <- 400

sites <- rtide::harmonics$Station %>%
  ps_longlat_to_sfc() %>%
  ps_activate_sfc() %>%
  select(Station, TZ) %>%
  ps_sfc_to_coords()


appCSS <- ".mandatory_star { color: red; }"







